### ISSUE TITLE
Probelm with index after filtering the language in the personal dictionary view

### ISSUE THREAD

**Issue by DenB10** [akvedi/lexicon#10]
Hi @akvedi 

First of all, thank you for continuing to develop the 'DictionaryAnywhere' extension and making it even better.

Can you reproduce this behavior:

1. Select a language in the options page, e.g. "French" in my case
2. Search for some French words
3. Search for an English word, e.g. 'switcher' -> No def in French (of course)
4. Select the English language as option -> Def found
5. Now, go to the personal dictionary: all searched words are there with correct defs if the language selector is set to "All". If you select "English", only one word is shown (Switcher), but it has the wrong definition, that of the first French word.
Screenshots for a better understanding:
![Presse-papiers-1](https://github.com/akvedi/lexicon/assets/9309147/c33fd83b-d424-4f34-8ba4-7565e78c30d3)
![Presse-papiers-2](https://github.com/akvedi/lexicon/assets/9309147/476e61b0-ec8b-4124-9685-86a29abacdf9)

I also have two suggestions for enhancementI, but perhaps I'll open up other issues so as not to mix things up?
I forgot: I've also implemented the extension's localization with two locales (en and fr). Let me know if you're interested.

Best regards,

@DenB10

**Comment by akvedi** [comment]
Thanks for the bug report @DenB10. I will fix it ASAP.  And yes it would be great to have this extension localized.

**Comment by DenB10** [comment]
@akvedi 
Okay, I'll present the localization and my various suggestions in another thread.

**Comment by akvedi** [comment]
Fixed in v1.6.0

**Comment by DenB10** [comment]
Hurrah! This is a good thing, because it was a very annoying bug.
But I'll have to wait until this version is released to test it...

**Comment by akvedi** [comment]
It is live. You can test it right now
