### ISSUE TITLE
Interpuncts are not removed from "More »" link

### ISSUE THREAD

**Issue by HatScripts** [akvedi/lexicon#2]
[Interpuncts](https://en.wikipedia.org/wiki/Interpunct) are not removed from the `More »` link.

For example, the word "dictionary" links to https://www.google.com/search?hl=en&q=define+dic%C2%B7tion%C2%B7ar%C2%B7y&gl=US ("define dic·tion·ar·y").

<img width="308" src="https://github.com/akvedi/lexicon/assets/5691865/a16efc1e-946e-4527-bb22-11fa18f939ed">

<img width="289" alt="Screenshot 2023-05-31 172142" src="https://github.com/akvedi/lexicon/assets/5691865/a526f793-4734-4ac1-b9af-a2c29f42795d">

**Comment by akvedi** [comment]
Fixed in version 1.2.1
