### ISSUE TITLE
Links in Google definitions cause truncation

### ISSUE THREAD

**Issue by HatScripts** [akvedi/lexicon#3]
* <img width="532" alt="Screenshot 2023-05-31 172528" src="https://github.com/akvedi/lexicon/assets/5691865/3cd9d197-be83-44ea-8d6d-1d7c4f885cdf">
* <img width="253" alt="Screenshot 2023-05-31 172551" src="https://github.com/akvedi/lexicon/assets/5691865/c4fb2dcd-46be-4e5c-ac94-714a211035a4">

**Comment by akvedi** [comment]
Fixed in version 1.2.1
