### ISSUE TITLE
[Feature request] How can I help making this add-on available for Brazilian Portuguese?

### ISSUE THREAD

**Issue by fabiorzfreitas** [akvedi/lexicon#7]
Perhaps for adding languages to the add-on, help from a native speaker could be useful/needed. Perhaps it doesn't require anything knowledge of the language at all and all that is needed is to write the code.

Well, I'm willing to help either way, if you could tell me what I need to do!

**Comment by akvedi** [comment]
Thank you so much for your kind offer to help. I truly appreciate your willingness to lend a hand. However, it doesn't require any knowledge of specific language to add it. I added Portuguese and Brazilian Portuguese in the dictionary.

One thing you can do to help is rate and reviews the extension on Firefox add on page.  Also star this repo and share it to others. It would really motivate me.

**Comment by akvedi** [comment]
Portuguese and Brazilian Portuguese are available in version 1.3.0.

**Comment by fabiorzfreitas** [comment]
Wow, I'm amazed by your kindness to answer and implement the request so quickly!

I don't think I'll have anyone to share the extension with, but I already starred the repo and I'm on my way to write a review!
