### ISSUE TITLE
Question: How do I add personal dictionary?

### ISSUE THREAD

**Issue by saitejapings** [akvedi/lexicon#9]
Hi @akvedi,

Thanks for the plugin, I was not able to add new names to my personal dictionary. I would want to add my own definitions/abbreviations for the the keywords. Ex: I want to map OMG to "Operational Mapping GPU". 

Is this possible with the plugin?

Thanks,
Sai.

**Comment by akvedi** [comment]
At the moment, you can't manually add a word to the personal dictionary. Words are added automatically when you look them up. Initially, I considered it, but couldn't find a compelling use case.
